/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Customer;

import Config.DatabaseConnection;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import model.Customer.AccountDetailsForm;
import model.Customer.CustomerForm;
import static ui.Customer.CreateAccountJPanel.con;
import ui.Security.ViewCustomerApplicationsPanel;

/**
 *
 * @author dattvi
 */
public class CardApplicationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CardApplicationJPanel
     */
    CustomerForm customerform;
    static Connection con;
    int userid;
    public CardApplicationJPanel(CustomerForm customerform) {
        initComponents();
         this.customerform = customerform;
         String loginArr[] = customerform.getLoginId().split("CT");
         this.userid = Integer.parseInt(loginArr[1]);
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAccountNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtOccupation = new javax.swing.JTextField();
        creditRadio = new javax.swing.JRadioButton();
        debitRadio = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        btnApplyCard = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APPLY FOR CARD");

        jLabel4.setText("Account Number");

        txtAccountNum.setEditable(false);

        jLabel5.setText("Card Holder's Name");

        txtName.setEditable(false);

        jLabel3.setText("Enter your salary");

        jLabel6.setText("Enter your occupation");

        cardGroup.add(creditRadio);
        creditRadio.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        creditRadio.setForeground(new java.awt.Color(102, 102, 102));
        creditRadio.setText("Credit");
        creditRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditRadioActionPerformed(evt);
            }
        });

        cardGroup.add(debitRadio);
        debitRadio.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        debitRadio.setForeground(new java.awt.Color(102, 102, 102));
        debitRadio.setText("Debit");
        debitRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitRadioActionPerformed(evt);
            }
        });

        jLabel7.setText("Which card do you want to apply for?");

        btnApplyCard.setText("APPLY");
        btnApplyCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(63, 63, 63)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(117, 117, 117)
                                .addComponent(creditRadio)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(63, 63, 63)
                                .addComponent(txtAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(debitRadio))
                        .addGap(118, 118, 118))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(btnApplyCard, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(creditRadio)
                    .addComponent(debitRadio))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(btnApplyCard, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
     private void populateFields(){
        ViewCustomerApplicationsPanel viewPanel = new ViewCustomerApplicationsPanel();
        
        AccountDetailsForm accountForm;
        try{
             
            
             CustomerForm form = viewPanel.getCustomerDetails(userid);
             txtName.setText(form.getName());
              ManageBankAccJPanel manageaccount = new ManageBankAccJPanel(customerform);
             accountForm = manageaccount.getAccountDetails(userid);
             txtAccountNum.setText(accountForm.getAccountNum());
             
            
             //txtBalance.setText(String.valueOf(accountForm.getTotalBalance()));
            
            
        }catch(Exception e){
            System.out.println("Exception in CardApplication.populateFields():"+e.getMessage());
            
        }
       
    }
    private void creditRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditRadioActionPerformed

    private void debitRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debitRadioActionPerformed

    private void btnApplyCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyCardActionPerformed
        // TODO add your handling code here:
        try{
            String name = txtName.getText();
            String accountNo = txtAccountNum.getText();
            creditRadio.setActionCommand("Credit");
            debitRadio.setActionCommand("Debit"); 
            double salary = Double.parseDouble(txtSalary.getText());
            String occupation =txtOccupation.getText();
            String  cardType = cardGroup.getSelection().getActionCommand();
            con = DatabaseConnection.DatabaseCon();
            Statement stat=con.createStatement();
            String insertQuery = "insert into card_application ( account_number, customerId, customerName, salary, occupation, creditlimit, appstatus, card_type) "
                    + "values(?,?,?,?,?,?,?,?)";
            CallableStatement cs = con.prepareCall(insertQuery);
           // cs.setString(1, "001");
            cs.setString(1, accountNo);
            cs.setInt(2, userid);
            cs.setString(3, name);
            cs.setDouble(4, salary);
            cs.setString(5, occupation);
            cs.setString(6, null);
            cs.setString(7, "PENDING");
            cs.setString(8, cardType);
            int count = cs.executeUpdate();
            if (count==1){
                String insertQuery2 = "INSERT INTO accountapplication (custId,processStatus,applicationStatus,applicationType) \n"  
                    + "values(?,?,?,?)";
            CallableStatement cs1 = con.prepareCall(insertQuery2);
           // cs.setString(1, "001");
            cs1.setInt(1, userid);
            cs1.setString(2, "PENDING");
            cs1.setString(3, "PENDING");
            cs1.setString(4, "CARDAPPLY");
            cs1.execute();
            JOptionPane.showMessageDialog(null,"Thankyou for applying for "+cardType+" card with us. Please wait for 48 hours for the update");
            cardGroup.clearSelection();
            txtOccupation.setText("");
            txtSalary.setText("");
            }
            
        }catch(Exception ex){
            System.out.println("ui.Customer.CardApplicationJPanel.btnApplyCardActionPerformed():"+ex.getMessage());
        }
        
    }//GEN-LAST:event_btnApplyCardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyCard;
    private javax.swing.ButtonGroup cardGroup;
    private javax.swing.JRadioButton creditRadio;
    private javax.swing.JRadioButton debitRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAccountNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
