/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Customer;

//import Config.ConnectionManager;
import Config.DatabaseConnection;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import utilities.Validations;

/**
 *
 * @author dattvi
 */
public class CreateAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAccountJPanel
     */
    Validations v;
    static Connection con;

    public CreateAccountJPanel() {
        initComponents();
        v = new Validations();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        accntTypeGroup = new javax.swing.ButtonGroup();
        txtContact = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        stateComboBox = new javax.swing.JComboBox<>();
        txtFatherName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        genMale = new javax.swing.JRadioButton();
        genFemale = new javax.swing.JRadioButton();
        genOther = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtPin = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMotherName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        cityComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        btnRegisterAccount = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtNationality = new javax.swing.JTextField();
        dobDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        savingsAccount = new javax.swing.JRadioButton();
        checkingAccount = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(165, 183, 195));

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("State");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Phone number");

        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming" }));
        stateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateComboBoxActionPerformed(evt);
            }
        });

        txtFatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFatherNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Father's name");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATE ACCOUNT");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date of Birth");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Account Holder's Name");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");

        genderGroup.add(genMale);
        genMale.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        genMale.setForeground(new java.awt.Color(102, 102, 102));
        genMale.setText("Male");
        genMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genMaleActionPerformed(evt);
            }
        });

        genderGroup.add(genFemale);
        genFemale.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        genFemale.setForeground(new java.awt.Color(102, 102, 102));
        genFemale.setText("Female");
        genFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genFemaleActionPerformed(evt);
            }
        });

        genderGroup.add(genOther);
        genOther.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        genOther.setForeground(new java.awt.Color(102, 102, 102));
        genOther.setText("Other");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pin");

        txtPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPinActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("City");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mother's name");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email");

        cityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cityComboBox.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                cityComboBoxComponentAdded(evt);
            }
        });
        cityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityComboBoxActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Age");

        btnRegisterAccount.setText("REGISTER");
        btnRegisterAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterAccountActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nationality");

        txtNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNationalityActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Account type");

        accntTypeGroup.add(savingsAccount);
        savingsAccount.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        savingsAccount.setForeground(new java.awt.Color(102, 102, 102));
        savingsAccount.setText("Savings");
        savingsAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsAccountActionPerformed(evt);
            }
        });

        accntTypeGroup.add(checkingAccount);
        checkingAccount.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        checkingAccount.setForeground(new java.awt.Color(102, 102, 102));
        checkingAccount.setText("Checking");
        checkingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingAccountActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(225, 163, 115));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DAG Intl. Fintech");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Your money is our responsibility");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(26, 26, 26))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel13)
                                .addComponent(jLabel6)))
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMotherName)
                                    .addComponent(cityComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(txtEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(genMale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(genFemale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(genOther))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(savingsAccount)
                                        .addGap(34, 34, 34)
                                        .addComponent(checkingAccount))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel10))
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(dobDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(143, 143, 143))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegisterAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(454, 454, 454))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dobDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(genMale)
                            .addComponent(genFemale)
                            .addComponent(genOther))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(savingsAccount)
                            .addComponent(checkingAccount))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnRegisterAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateComboBoxActionPerformed
        // TODO add your handling code here:
        //set city
        if (stateComboBox.getSelectedItem() == "Alabama") {
            cityComboBox.removeAllItems();
            cityComboBox.addItem("Birmingham");
            cityComboBox.addItem("Huntsville");
            cityComboBox.addItem("Montgomery");

        } else if (stateComboBox.getSelectedItem() == "California") {
            cityComboBox.removeAllItems();
            cityComboBox.addItem("Los Angeles");
            cityComboBox.addItem("San Diego");
            cityComboBox.addItem("San Jose");
            cityComboBox.addItem("San Francisco");
            cityComboBox.addItem("Fresno");

        } else if (stateComboBox.getSelectedItem() == "Massachusetts") {
            cityComboBox.removeAllItems();
            cityComboBox.addItem("Boston");
            cityComboBox.addItem("Worcester");
            cityComboBox.addItem("Springfield");
            cityComboBox.addItem("Cambridge");
            cityComboBox.addItem("Lowell");

        } else if (stateComboBox.getSelectedItem() == "New York") {
            cityComboBox.removeAllItems();
            cityComboBox.addItem("New York City");
            cityComboBox.addItem("Buffalo");
            cityComboBox.addItem("Rochester");
            cityComboBox.addItem("Yonkers");
            cityComboBox.addItem("Syracuse");

        } else if (stateComboBox.getSelectedItem() == "New York") {
            cityComboBox.removeAllItems();
            cityComboBox.addItem("New York City");
            cityComboBox.addItem("Buffalo");
            cityComboBox.addItem("Rochester");
            cityComboBox.addItem("Yonkers");
            cityComboBox.addItem("Syracuse");

        } else if (stateComboBox.getSelectedItem() == "Texas") {
            cityComboBox.removeAllItems();
            cityComboBox.addItem("Houston");
            cityComboBox.addItem("San Antonio");
            cityComboBox.addItem("Dallas");
            cityComboBox.addItem("Austin");
            cityComboBox.addItem("Fort Worth");

        }
    }//GEN-LAST:event_stateComboBoxActionPerformed

    private void txtFatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFatherNameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void genMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genMaleActionPerformed

    private void genFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genFemaleActionPerformed

    private void txtPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinActionPerformed

    private void cityComboBoxComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cityComboBoxComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_cityComboBoxComponentAdded

    private void cityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityComboBoxActionPerformed
        // TODO add your handling code here:
        Object item1 = cityComboBox.getSelectedItem();

    }//GEN-LAST:event_cityComboBoxActionPerformed

    private String convertDateToString(Date inputDate) {
        String parseDt = null;
        try {
            Date dt = inputDate;
            SimpleDateFormat pattern = new SimpleDateFormat("MM/dd/yyyy");
            parseDt = pattern.format(dt);

        } catch (Exception ex) {
            ex.printStackTrace();
            return null;
        }
        return parseDt;
    }
    private void btnRegisterAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterAccountActionPerformed
        // TODO add your handling code here:
        int age = 0;
        double accountno;

        String name, dob, gender = "", address, state = "", city = "", nationality, fathersname, mothersname, email, accType = "", pin, phoneno;
        if (txtName.getText().equals("")
                || txtAge.getText().equals("")
                || txtAddress.getText().equals("")
                || txtPin.getText().equals("")
                || txtNationality.getText().equals("")
                || txtFatherName.getText().equals("")
                || txtMotherName.getText().equals("")
                || txtContact.getText().equals("")
                || txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter the details");
            return;
        }
//        
//        age = Integer.parseInt(txtAge.getText());
        //int id;

        genMale.setActionCommand("Male");
        genFemale.setActionCommand("Female");
        genOther.setActionCommand("Other");
        savingsAccount.setActionCommand("SAVINGS");
        checkingAccount.setActionCommand("CHECKING");

        name = txtName.getText();
        age = Integer.parseInt(txtAge.getText());
        gender = genderGroup.getSelection().getActionCommand();
        address = txtAddress.getText();
        state = stateComboBox.getSelectedItem().toString();
        city = cityComboBox.getSelectedItem().toString();
        pin = txtPin.getText();
        nationality = txtNationality.getText();
        fathersname = txtFatherName.getText();
        mothersname = txtMotherName.getText();
        phoneno = txtContact.getText();
        email = txtEmail.getText();
        accType = accntTypeGroup.getSelection().getActionCommand();
        String date = convertDateToString(dobDateChooser.getDate());
        System.out.println("Formatted Date: " + date);

        //id=Integer.parseInt(tf1.getText());
        if (v.isValidName(txtName.getText())) {
            System.out.println("correct name");
        } else {
            txtName.setText("");
            JOptionPane.showMessageDialog(this, "Enter correct name");
        }
        if (v.onlyDigits(txtAge.getText())) {
            System.out.println("correct age");
        } else {
            txtAge.setText("");
            JOptionPane.showMessageDialog(this, "Enter correct age");
        }

        if (v.isValidString(txtAddress.getText())) {
            System.out.println("correct address");
        } else {
            txtAddress.setText("");
            JOptionPane.showMessageDialog(this, "Enter correct address");
        }
        if (v.isValidPin(txtPin.getText())) {
            System.out.println("correct pin");
        } else {
            txtPin.setText("");
            JOptionPane.showMessageDialog(this, "Enter correct pin");
        }
        if (v.isValidString(txtNationality.getText())) {
            System.out.println("correct nationality");
        } else {
            txtNationality.setText("");
            JOptionPane.showMessageDialog(this, "Enter correct nationality");
        }
        if (v.isValidString(txtFatherName.getText())) {
            System.out.println("correct fathers name");
        } else {
            txtFatherName.setText("");
            JOptionPane.showMessageDialog(this, "Enter correct fathers name");
        }
        if (v.isValidString(txtMotherName.getText())) {
            System.out.println("correct mothers name");
        } else {
            txtMotherName.setText("");
            JOptionPane.showMessageDialog(this, "Enter correct mothers name");
        }
        if (v.isValidPhoneNumber(txtContact.getText())) {
            System.out.println("correct contact");
        } else {
            txtContact.setText("");
            JOptionPane.showMessageDialog(this, "Enter correct contact");
        }
        if (v.isValidEmail(txtEmail.getText())) {
            System.out.println("correct email");
        } else {
            txtEmail.setText("");
            JOptionPane.showMessageDialog(this, "Enter correct email");
        }

        if (v.isValidName(txtName.getText())
                && v.onlyDigits(txtAge.getText())
                && v.isValidString(txtAddress.getText())
                && v.isValidPin(txtPin.getText())
                && v.isValidString(txtNationality.getText())
                && v.isValidString(txtFatherName.getText())
                && v.isValidString(txtMotherName.getText())
                && v.isValidPhoneNumber(txtContact.getText())
                && v.isValidEmail(txtEmail.getText())) {

            int balance = 0;

            try {

                con = DatabaseConnection.DatabaseCon();
                Statement stat = con.createStatement();
                String insertQuery = "insert into customer ( customerName, age, gender, date_of_birth, address, city, state, pin, nationality, fathers_name, mothers_name, phone_number, email, activeState,account_type) "
                        + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                CallableStatement cs = con.prepareCall(insertQuery);
                // cs.setString(1, "001");
                cs.setString(1, name);
                cs.setInt(2, age);
                cs.setString(3, gender);
                cs.setString(4, date);
                cs.setString(5, address);
                cs.setString(6, "Boston");
                cs.setString(7, "MA");
                // cs.setString(8, "United States");
                cs.setString(8, pin);
                cs.setString(9, nationality);
                cs.setString(10, fathersname);
                cs.setString(11, mothersname);
                cs.setString(12, phoneno);
                cs.setString(13, email);
                cs.setString(14, "N");
                cs.setString(15, accType);

                //cs.setString(16,"PENDING");
                cs.execute();
                String slectQry = "SELECT LAST_INSERT_ID()";
                int id = 0;
                ResultSet rs = stat.executeQuery(slectQry);
                while (rs.next()) {
                    id = rs.getInt(1);
                }
                String insertQuery2 = "INSERT INTO accountapplication (custId,processStatus,applicationStatus,applicationType) \n"
                        + "values(?,?,?,?)";
                CallableStatement cs1 = con.prepareCall(insertQuery2);
                // cs.setString(1, "001");
                cs1.setInt(1, id);
                cs1.setString(2, "PENDING");
                cs1.setString(3, "PENDING");
                cs1.setString(4, "REGISTER");
                cs1.execute();
                JOptionPane.showMessageDialog(null, "Successfully registered. Please check mail for the status");

                txtName.setText("");
                txtAddress.setText("");
                txtAge.setText("");
                txtPin.setText("");
                txtContact.setText("");
                txtNationality.setText("");
                accntTypeGroup.clearSelection();
                genderGroup.clearSelection();
                txtFatherName.setText("");
                txtMotherName.setText("");
                txtEmail.setText("");
                con.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Enter Correct Details!");
        }
    }//GEN-LAST:event_btnRegisterAccountActionPerformed

    private void txtNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNationalityActionPerformed

    private void savingsAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsAccountActionPerformed

    private void checkingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup accntTypeGroup;
    private javax.swing.JButton btnRegisterAccount;
    private javax.swing.JRadioButton checkingAccount;
    private javax.swing.JComboBox<String> cityComboBox;
    private com.toedter.calendar.JDateChooser dobDateChooser;
    private javax.swing.JRadioButton genFemale;
    private javax.swing.JRadioButton genMale;
    private javax.swing.JRadioButton genOther;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton savingsAccount;
    private javax.swing.JComboBox<String> stateComboBox;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtMotherName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JTextField txtPin;
    // End of variables declaration//GEN-END:variables
}
