/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Customer;

import Config.DatabaseConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Customer.AccountDetailsForm;
import model.Customer.CustomerForm;
import ui.Security.ViewCustomerApplicationsPanel;

/**
 *
 * @author dattvi
 */
public class ManageBankAccJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageBankAccJPanel
     */
    CustomerForm customerform;
    static Connection con;
    int userid;
    public ManageBankAccJPanel(CustomerForm customerform) {
        initComponents();
        this.customerform = customerform;
         String loginArr[] = customerform.getLoginId().split("CT");
         this.userid = Integer.parseInt(loginArr[1]);
        populateFields();
        populateTransactionTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblTransaction = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAccountNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        btnAddAmount = new javax.swing.JButton();
        btnWithdrawAmt = new javax.swing.JButton();

        setBackground(new java.awt.Color(165, 183, 195));

        tblTransaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction_id", "Transaction Type", "Amount", "Date of Transaction", "Balance"
            }
        ));
        jScrollPane2.setViewportView(tblTransaction);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE ACCOUNT");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Name");

        txtName.setEditable(false);

        txtAccountNum.setEditable(false);
        txtAccountNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountNumActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Balance");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Account number");

        txtBalance.setEditable(false);
        txtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBalanceActionPerformed(evt);
            }
        });

        btnAddAmount.setText("Add Amount");
        btnAddAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAmountActionPerformed(evt);
            }
        });

        btnWithdrawAmt.setText("Withdraw amount");
        btnWithdrawAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawAmtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btnAddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnWithdrawAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithdrawAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void populateFields(){
        ViewCustomerApplicationsPanel viewPanel = new ViewCustomerApplicationsPanel();
        CustomerProfileJPanel profilePanel = new CustomerProfileJPanel(customerform);
        AccountDetailsForm accountForm;
        try{
             
            
             CustomerForm form = viewPanel.getCustomerDetails(userid);
             txtName.setText(form.getName());
             txtAccountNum.setText(profilePanel.getAccountNum(userid));
             accountForm = getAccountDetails(userid);
             txtBalance.setText(String.valueOf(accountForm.getTotalBalance()));
            
            
        }catch(Exception e){
            System.out.println("Exception in CustomerProfileJPanel.populateFields():"+e.getMessage());
            
        }
       
    }
    private void populateTransactionTable(){
        //transaction_details
         AccountDetailsForm accountForm;
        DefaultTableModel model = (DefaultTableModel) tblTransaction.getModel();
        model.setRowCount(0);

        try {
            con = DatabaseConnection.DatabaseCon();
            Statement st = con.createStatement();
            accountForm = getAccountDetails(userid);
            ResultSet rs = st.executeQuery("select * from transaction_details where account_no='"+accountForm.getAccountNum()+"'");
            while (rs.next()) {
                String type = rs.getString("transaction_type");
                model.addRow(new Object[]{
                    rs.getInt("transaction_id"),
                    rs.getString("transaction_type"),
                    rs.getString("transaction_amount"),
                    rs.getString("date"),
                    rs.getString("current_balance"),
                    
                    
                });
//               rs.getString("activeState")
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    public AccountDetailsForm getAccountDetails(int userid){
        AccountDetailsForm form = new AccountDetailsForm();
        try{
            con = DatabaseConnection.DatabaseCon();
        
            
            String query = "select * from account_details where customerId="+userid;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            if (rs.next()){
                form.setAccountNum(rs.getString("account_number"));
                form.setAccType(rs.getString("type"));
                form.setCreditCardActive(rs.getString("creditCardActive"));
                form.setDebitCardActive(rs.getString("debitCardActive"));
                form.setCreditNo(rs.getString("creditNumber"));
                form.setDebitNo(rs.getString("debitNumber"));
                form.setCreditLimit(rs.getString("creditLimit"));
                form.setTotalBalance((rs.getDouble("totalBalance")));
                
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ViewCustomerApplicationsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return form;
    }
    private void txtAccountNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountNumActionPerformed

    private void txtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceActionPerformed

    private void btnAddAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAmountActionPerformed
        // TODO add your handling code here:
        AccountDetailsForm form = getAccountDetails(userid);
        String accNo=form.getAccountNum();

        AddamountJPanel a=new AddamountJPanel(accNo);
        a.setVisible(true);
        
    }//GEN-LAST:event_btnAddAmountActionPerformed

    private void btnWithdrawAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawAmtActionPerformed
        // TODO add your handling code here:
        AccountDetailsForm form = getAccountDetails(userid);
        String accNo=form.getAccountNum();
        
        WithdrawAmtJPanel w=new WithdrawAmtJPanel(accNo);
        w.setVisible(true);
       
    }//GEN-LAST:event_btnWithdrawAmtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAmount;
    private javax.swing.JButton btnWithdrawAmt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTransaction;
    private javax.swing.JTextField txtAccountNum;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
