/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Customer;

import Config.DatabaseConnection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import model.Customer.CustomerForm;
import static ui.Customer.WithdrawAmtJPanel.con;
import utilities.CommonUtilities;
import utilities.Validations;

/**
 *
 * @author dattvi
 */
public class TransactionsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TransactionsJPanel
     */
    String accNum;
    static Connection con;
    Timer timer;
    Validations v;
    public TransactionsJPanel(String accNum) {
        initComponents();
        this.accNum = accNum;
        v = new Validations();
         txtAccountNum.setText(accNum);
        setBalance(accNum);
        ActionListener actionListner = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               Date date = new Date();
               DateFormat df = new SimpleDateFormat("HH:mm:ss");
               String time = df.format(date);
               txtClock.setText(time);
               
               Date date1 = new Date();
               DateFormat df1 = new SimpleDateFormat("mm/dd/yyyy");
               String currdate = df1.format(date);
            }
        };
        timer = new Timer(1000, actionListner);
        timer.setInitialDelay(0);
        timer.start();
        txtTimestamp.setText(String.valueOf(CommonUtilities.currDatetime())+" "+txtClock.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtClock = new javax.swing.JLabel();
        txtTimestamp = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        txtCurrentBalance = new javax.swing.JTextField();
        txtAccountNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnTransferAmount = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtRecAccountNum = new javax.swing.JTextField();

        setBackground(new java.awt.Color(165, 183, 195));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANSACTIONS");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sender's Account Number");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Balance");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Amount");

        txtClock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtClock.setForeground(new java.awt.Color(255, 51, 51));

        txtTimestamp.setEditable(false);

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        txtCurrentBalance.setEditable(false);
        txtCurrentBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurrentBalanceActionPerformed(evt);
            }
        });

        txtAccountNum.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date");

        btnTransferAmount.setText("Transfer money");
        btnTransferAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferAmountActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Recipient's Account Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(txtClock, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTimestamp, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                            .addComponent(txtRecAccountNum)
                            .addComponent(txtAccountNum)
                            .addComponent(txtCurrentBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                            .addComponent(txtAmount)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(btnTransferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtClock, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRecAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTimestamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnTransferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(425, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

      private void setBalance(String accNum){
        try{
            con = DatabaseConnection.DatabaseCon();
            Statement s=con.createStatement();
            String qry = "Select totalBalance from account_details where account_number = '"+accNum+"' ";
            
             ResultSet rs = s.executeQuery(qry); 
                if(rs.next())
                {
                    String cb=rs.getString(1);
                    txtCurrentBalance.setText(cb);
                   // currbal=Integer.parseInt(cb);
                }      
        }catch(Exception e){
            System.out.println("Exception in Customer.AddamountJPanel.setBalance():"+e.getMessage());
        }
       
    }
    private void btnTransferAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferAmountActionPerformed
        // TODO add your handling code here:
        double balance=0.00,bal=0.00,amt=0.00,current_bal=0.00;
        char arr[]=new char[28];

        String type;
        String date,accountNum;
       //String receipientAcc = txtRecAccountNum.getText();
       if (!( v.onlyDigits(txtAmount.getText()))){
            JOptionPane.showMessageDialog(this, "Enter only digits for amount.");
        }
       if(txtRecAccountNum.getText().equals("")||txtRecAccountNum.getText().equals(null)){
           JOptionPane.showMessageDialog(this, "Enter receipient account number");
       }
        accountNum=txtAccountNum.getText();
        bal=Double.parseDouble(txtCurrentBalance.getText());
        amt=Double.parseDouble(txtAmount.getText());
        // type=tf4.getText();
        date=txtTimestamp.getText().trim();
        String recAccountNum = txtRecAccountNum.getText().trim();
        
        
        
        try
        {
            if(isAccountValid()){
            con = DatabaseConnection.DatabaseCon();
            Statement s = con.createStatement();
            String qry = "Select totalBalance from account_details where account_number='"+accountNum+"'";
            ResultSet rs = s.executeQuery(qry);
            if(rs.next())
            {
                String cb=rs.getString(1);
                balance=Double.parseDouble(cb);
            }
            current_bal = balance-amt;

            String insertQry = "Insert into transaction_details ( account_no, transaction_amount, current_balance, date,transaction_type,recipient_account_no)"
            + "values('"+accountNum+"',"+amt+","+current_bal+",'"+date+"','TRANSFER','"+txtRecAccountNum.getText().trim()+"')";
            int count =  s.executeUpdate(insertQry);
            if(count==1){
                 Statement s1 = con.createStatement();
                double recBal=0.00,newBal=0.00;
                String selectQry="Select totalBalance from account_details where account_number='"+recAccountNum+"'";
                ResultSet rs1 = s1.executeQuery(selectQry);
                if(rs1.next())
                {
                    String cb=rs1.getString(1);
                    recBal=Double.parseDouble(cb);
                }
                newBal = recBal + amt;
                String update = "update account_details set totalBalance="+newBal+" where account_number='"+recAccountNum+"'";
                int count1 =  s1.executeUpdate(update);
                
                JOptionPane.showMessageDialog(null,"Amount transferred successfully");
                changedamount();
            }else{
                JOptionPane.showMessageDialog(null,"Failed to transfer money to the account");
            }
            }else{
                 JOptionPane.showMessageDialog(null,"Invalid account number");
                 txtRecAccountNum.setText("");
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnTransferAmountActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtCurrentBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentBalanceActionPerformed
    
    private boolean isAccountValid(){
         int count=0;
          boolean flag = false;
        try{
            con = DatabaseConnection.DatabaseCon();
            Statement s = con.createStatement();
            String accountNum = txtRecAccountNum.getText().trim();
           
            String qry = "Select count(*) from account_details where account_number ='"+accountNum+"'";
            ResultSet rs = s.executeQuery(qry);
            if(rs.next())
            {
               count = rs.getInt(1);
               if(count!=1)
                flag = false;
               else
                 flag=true;
            }
           
        }catch(Exception e){
            System.out.println("ui.Customer.TransactionsJPanel.txtRecAccountNumInputMethodTextChanged():"+e.getMessage());
            flag = false;
        }
        return flag;
    }
    
    public void changedamount()
    {
      double bal,amt;
        String id;
        id=txtAccountNum.getText();
        bal=Double.parseDouble(txtCurrentBalance.getText());
        amt=Double.parseDouble(txtAmount.getText());
        try
        {
            con = DatabaseConnection.DatabaseCon();
            Statement s=con.createStatement();
            bal=bal-amt;
            String updQry = "Update account_details set totalBalance="+bal+" where account_number='"+id+"' ";
            int count = s.executeUpdate(updQry);
            if(count == 1){
                txtCurrentBalance.setText(String.valueOf(bal));
                txtAmount.setText("");
            }
//JOptionPane.showMessageDialog(null,"Record updated successfully");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferAmount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAccountNum;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JLabel txtClock;
    private javax.swing.JTextField txtCurrentBalance;
    private javax.swing.JTextField txtRecAccountNum;
    private javax.swing.JTextField txtTimestamp;
    // End of variables declaration//GEN-END:variables
}
