/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui.Customer;

import Config.DatabaseConnection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import static ui.Customer.AddamountJPanel.con;
import utilities.CommonUtilities;

/**
 *
 * @author DELL
 */
public class WithdrawAmtJPanel extends javax.swing.JFrame {

    /** Creates new form Withdrawamount */
    /** Creates new form Withdraw amount */
    public WithdrawAmtJPanel() {
        //initComponents();
    }
    static Connection con;
     Timer timer;
    public WithdrawAmtJPanel(String accid)
    {
        initComponents();
       txtAccountNum.setText(""+accid);
        setBalance(accid);
        ActionListener actionListner = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               Date date = new Date();
               DateFormat df = new SimpleDateFormat("HH:mm:ss");
               String time = df.format(date);
               txtClock.setText(time);
               
               Date date1 = new Date();
               DateFormat df1 = new SimpleDateFormat("mm/dd/yyyy");
               String currdate = df1.format(date);
            }
        };
        timer = new Timer(1000, actionListner);
        timer.setInitialDelay(0);
        timer.start();
        txtTimestamp.setText(String.valueOf(CommonUtilities.currDatetime())+" "+txtClock.getText());
    }
    
    private void setBalance(String accNum){
        try{
            con = DatabaseConnection.DatabaseCon();
            Statement s=con.createStatement();
            String qry = "Select totalBalance from account_details where account_number = '"+accNum+"' ";
            
             ResultSet rs = s.executeQuery(qry); 
                if(rs.next())
                {
                    String cb=rs.getString(1);
                    txtCurrentBalance.setText(cb);
                   // currbal=Integer.parseInt(cb);
                }      
        }catch(Exception e){
            System.out.println("Exception in Customer.AddamountJPanel.setBalance():"+e.getMessage());
        }
       
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWithdrawAmount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAccountNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTimestamp = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        txtCurrentBalance = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtClock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnWithdrawAmount.setText("WITHDRAW");
        btnWithdrawAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawAmountActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WITHDRAW AMOUNT");

        txtAccountNum.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Account Number");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Balance");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Amount");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setText("Date");

        txtTimestamp.setEditable(false);

        txtCurrentBalance.setEditable(false);

        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 519, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnWithdrawAmount)
                                .addGap(128, 128, 128)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTimestamp, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(486, 486, 486))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtClock, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtClock, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(txtTimestamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jLabel6)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithdrawAmount)
                    .addComponent(jButton1))
                .addContainerGap(377, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnWithdrawAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawAmountActionPerformed
        // TODO add your handling code here:
        double balance=0.00,bal=0.00,amt=0.00,current_bal=0.00;
        char arr[]=new char[28];
        
        String type;
        String date,accountNum;
        accountNum=txtAccountNum.getText();
        bal=Double.parseDouble(txtCurrentBalance.getText());
        amt=Double.parseDouble(txtAmount.getText());
       // type=tf4.getText();
        date=txtTimestamp.getText().trim();  
       
       /*
        5-7 month  9-10 date   25-28 year
        */
       
       //System.out.println(arr);
       //System.out.println("" + arr.length);
        //for(int i=0;i<date.length();i++)
        //{
          //  System.out.print(arr[i]);
        //}
       //String str=arr[4]+arr[5]+arr[6]+"-"+arr[8]+arr[9]+"-"+arr[24]+arr[25]+arr[26]+arr[27];
       //System.out.println(str);
        //changedamount();
        try
        {
            con = DatabaseConnection.DatabaseCon();
           Statement s = con.createStatement();
            String qry = "Select totalBalance from account_details where account_number='"+accountNum+"'";
            ResultSet rs = s.executeQuery(qry); 
            if(rs.next())
            {
                String cb=rs.getString(1);
                balance=Double.parseDouble(cb);
            }    
            current_bal = balance-amt;
            
            String insertQry = "Insert into transaction_details ( account_no, transaction_amount, current_balance, date,transaction_type)"
                    + "values('"+accountNum+"',"+amt+","+current_bal+",'"+date+"','WITHDRAWN')";
           int count =  s.executeUpdate(insertQry);
           if(count==1){
            JOptionPane.showMessageDialog(null,"Amount withdrawn successfully");
            changedamount();
           }else{
               JOptionPane.showMessageDialog(null,"Failed to withdraw money from the account");
           }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnWithdrawAmountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //        BalanceInfoJPanel b=new BalanceInfoJPanel();
        //        b.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

     public void changedamount()
    {
      double bal,amt;
        String id;
        id=txtAccountNum.getText();
        bal=Double.parseDouble(txtCurrentBalance.getText());
        amt=Double.parseDouble(txtAmount.getText());
        try
        {
            con = DatabaseConnection.DatabaseCon();
            Statement s=con.createStatement();
            bal=bal-amt;
            String updQry = "Update account_details set totalBalance="+bal+" where account_number='"+id+"' ";
            int count = s.executeUpdate(updQry);
            if(count == 1){
                txtCurrentBalance.setText(String.valueOf(bal));
                txtAmount.setText("");
            }
//JOptionPane.showMessageDialog(null,"Record updated successfully");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WithdrawAmtJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WithdrawAmtJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WithdrawAmtJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WithdrawAmtJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WithdrawAmtJPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnWithdrawAmount;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAccountNum;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JLabel txtClock;
    private javax.swing.JTextField txtCurrentBalance;
    private javax.swing.JTextField txtTimestamp;
    // End of variables declaration//GEN-END:variables

}
